# Shell variables
# Generated by 'wal'
wallpaper='/home/ohsystemmm/Downloads/nanahoshi_1.jpg'

# Special
background='#121819'
foreground='#e8e4df'
cursor='#e8e4df'

# Colors
color0='#121819'
color1='#6D7985'
color2='#628787'
color3='#788992'
color4='#9DA2A3'
color5='#D2B3B1'
color6='#CAC5BA'
color7='#e8e4df'
color8='#a29f9c'
color9='#6D7985'
color10='#628787'
color11='#788992'
color12='#9DA2A3'
color13='#D2B3B1'
color14='#CAC5BA'
color15='#e8e4df'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
