InstallRequired() {
  Packages=(
    blueman
    bluez
    bluez-utils
    brightnessctl
    btop
    cliphist
    dolphin
    mako
    fastfetch
    fish
    git
    noto-fonts
    pavucontrol
    sddm
    papirus-icon-theme
    pipewire
    pipewire-alsa
    pipewire-jack
    pipewire-pulse
    python-click
    python-gobject
    python-pip
    python-psutil
    python-pywal
    python-rich
    rofi-wayland
    ttf-cascadia-code
    ttf-fira-code
    ttf-fira-sans
    ttf-firacode-nerd
    ttf-hanazono
    noto-fonts-emoji
    xdg-desktop-portal
    xdg-desktop-portal-gtk
    xdg-desktop-portal-wlr
    xdg-desktop-portal-hyprland
    xdg-user-dirs
    libpulse
    network-manager-applet
    networkmanager
    nm-connection-editor
    nwg-look
    breeze-icons
    gum
    gtk4
    gtk3
    gst-plugin-pipewire
    xarchiver
    wireplumber
    hyprland
    slurp
    tumbler
    grim
    libadwaita
    chromium
    fd
    hypridle
    hyprland
    hyprlock
    swww
    hyprshade
    waybar
    wlogout
    bibata-cursor-theme
    waypaper
    aylurs-gtk-shell
    figlet
    zsh-syntax-highlighting 
    autojump 
    zsh-autosuggestions
    oh-my-zsh
    firefox-nightly-bin
    wezterm
  )
  paru -S --needed "${Packages[@]}" --noconfirm
}

InstallOptional() {
  Packages=(
    man-pages
    neovim
    timeshift
    unzip
    zip
    vim
    vlc
    wget
    imagemagick
    tree
    cava
    paru
    parui
    wayland-screenshot
    imgcat 
    emote
  )
  paru -S --needed "${Packages[@]}" --noconfirm
}

InstallohSystemmm() {
  Packages=(
    tlp
    krita
    prismlauncher
    blender
    wine
    syncplay
    steam
    ani-cli
    mov-cli
    manga-cli-git
    armcord-bin
    spotify
    spotify-adblock
    whatsapp-for-linux
    signal-desktop
    wps-office
    fcitx5
    fcitx5-configtool
    mozc
    obs-studio
  )
  paru -S --needed "${Packages[@]}" --noconfirm
}
