theme = "tokyonight"
[editor]
auto-completion = true
auto-format = true
bufferline = "multiple"
cursorline = true
line-number = "relative"
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "╎"
render = true

[editor.smart-tab]
enable = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.statusline.mode]
insert = "Insert"
normal = "Normal"
select = "Select"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
