#        _                 _ _   _          _                  _ 
#   __ _| | __ _  ___ _ __(_) |_| |_ _   _ | |_ ___  _ __ ___ | |
#  / _` | |/ _` |/ __| '__| | __| __| | | || __/ _ \| '_ ` _ \| |
# | (_| | | (_| | (__| |  | | |_| |_| |_| || || (_) | | | | | | |
#  \__,_|_|\__,_|\___|_|  |_|\__|\__|\__, (_)__\___/|_| |_| |_|_|
#                                    |___/                       
#
# by ohSystemmm <3 - 2024

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 0.7

[window.padding]
x = 15
y = 15
